---
- name: 'register local path'
  stat:
    path: "{{ build_path }}"
  register: build_path_dir
  tags: init

- name: set 'bind_ip' if 'docker_bind_ip' is defined
  ansible.builtin.set_fact:
     bind_ip: "{{ docker_bind_ip + ':' }}"
  when: docker_bind_ip is defined
  tags: init

- name: set 'bind_ip' if 'docker_bind_ip' is undefined
  ansible.builtin.set_fact:
     bind_ip: ""
  when: docker_bind_ip is undefined
  tags: init

- name: set 'registry_url' if 'docker_registry_url' is defined
  ansible.builtin.set_fact:
     registry_url: "{{ docker_registry_url + '/' }}"
  when: docker_registry_url is defined
  tags: init

- name: set 'registry_url' if 'docker_registry_url' is undefined
  ansible.builtin.set_fact:
     registry_url: ""
  when: docker_registry_url is undefined
  tags: init

- name: "create local path"
  file:
    path: '{{ build_path }}'
    state: directory
    recurse: yes
    mode: 0775
  when: not build_path_dir.stat.exists
  tags: init

- name: generate composer file
  template:
    src: docker-compose.yml.j2
    dest: '{{ build_path }}/{{ project }}.yml'
    mode: preserve
  tags: init

- name: generate control files
  template:
    src: control.j2
    dest: '{{ build_path }}/{{ project }}'
    mode: '+x'
  tags: init

- name: generate Makefile
  template:
    src: Makefile
    dest: '{{ build_path }}/Makefile'
    mode: preserve
  tags: init
