# https://hub.docker.com/r/onlyoffice/documentserver/tags?page=1&ordering=last_updated
FROM onlyoffice/documentserver:{{ conf['docker_tag_nextcloud_onlyoffice_ds']|default("6.2") }}

LABEL project="{{ project }}"
