---
- name: Deploy local
  hosts: "sonet_local"
  roles:
    - role: './roles/services'
  vars:
    build_path: "{{ local_playbook_path }}/../../build/sonet_local/source"
    docker_data_path: "{{ local_playbook_path }}/../../build/sonet_local/data"
    backup_path: "{{ local_playbook_path }}/../../build/sonet_local/backup"
    pki_path: "{{ local_playbook_path }}/../../build/sonet_local/pki"
    docker_bind_ip: 127.0.0.1
    # docker_bind_ip: "{{ ansible_default_ipv4['address']|string }}"
    # docker_registry_url: "registry.sonet.local:5000"
    generate_service_certs: true
    include_service:
      - caddy
      - coredns
      - openldap
      - phpldapadmin
      - redmine
      - excalidraw
      - gitlab
      - roundcube
      - mailserv
      - storage
      - nextcloud
      - portainer
      - adminer
      - grafana
      - monitoring
      - control-files
  vars_files:
    - vars/10-vault.yml
    - vars/90-general.yml
    - vars/99-override.yml
