# https://hub.docker.com/r/excalidraw/excalidraw/tags?page=1&ordering=last_updated
FROM excalidraw/excalidraw:{{ sonet_general['docker_tag_excalidraw']|default("latest") }}

LABEL project="{{ project }}"
