# https://hub.docker.com/r/jgraph/export-server/tags?page=1&ordering=last_updated
FROM jgraph/export-server:{{ conf['docker_tag_nextcloud_drawio_export_server']|default("latest") }}

LABEL project="{{ project }}"
