---
- name: generate composer file
  template:
    src: control-files/docker-compose.yml
    dest: '{{ build_path }}/{{ project }}.yml'
    mode: preserve
  tags: init

- name: generate control files
  template:
    src: control-files/control.sh
    dest: '{{ build_path }}/{{ project }}'
    mode: '+x'
  tags: init

- name: generate Makefile
  template:
    src: control-files/Makefile
    dest: '{{ build_path }}/Makefile'
    mode: preserve
  tags: init
