---
- name: "services : create build folder {{ build_path }}/images"
  file:
    path: '{{ build_path }}/images'
    state: directory
    recurse: yes
    mode: 0775
  tags: init

- name: set 'bind_ip' if 'docker_bind_ip' is defined
  ansible.builtin.set_fact:
    bind_ip: "{{ docker_bind_ip + ':' }}"
  when: docker_bind_ip is defined
  tags: init

- name: set 'bind_ip' if 'docker_bind_ip' is undefined
  ansible.builtin.set_fact:
    bind_ip: ""
  when: docker_bind_ip is undefined
  tags: init

- debug:
    var: bind_ip

- name: set 'registry_url' if 'docker_registry_url' is defined
  ansible.builtin.set_fact:
    registry_url: "{{ docker_registry_url + '/' }}"
  when: docker_registry_url is defined
  tags: init

- name: set 'registry_url' if 'docker_registry_url' is undefined
  ansible.builtin.set_fact:
    registry_url: ""
  when: docker_registry_url is undefined
  tags: init

- debug:
    var: registry_url

- name: "setup pki"
  include_tasks: 'setup_pki.yml'
  when: generate_service_certs is defined and generate_service_certs == True
  tags: init

- name: "include services"
  include_tasks: '{{ service }}.yml'
  loop: '{{ include_service|default([]) }}'
  loop_control:
    loop_var: service
  tags: [init, build, push]
