---
- name: "services : create build folder {{ build_path }}/images"
  file:
    path: '{{ build_path }}/images'
    state: directory
    recurse: yes
    mode: 0775
  tags: init

- name: "setup pki"
  include_tasks: 'setup_pki.yml'
  when: generate_service_certs
  tags: init

- name: "include services"
  include_tasks: '{{ service }}.yml'
  loop: '{{ include_service|default([]) }}'
  loop_control:
    loop_var: service
  tags: [init, build, push]
