---
- name: 'portainer : service init'
  include_tasks: service_common.yml
  vars:
    - service_name: portainer
    - service_image_dir: '{{ build_path }}/images/portainer'
  tags: [init, build, push]
