# https://hub.docker.com/r/osixia/phpldapadmin/tags?page=1&ordering=last_updated
FROM osixia/phpldapadmin:{{ sonet_general['docker_tag_phpldapadmin']|default("stable-amd64") }}

LABEL project="{{ project }}"
